import { test } from 'node:test'
import assert from 'node:assert/strict'
import { makeJourney, completeAction, stageChange, health, localDate, ISLAND_AREAS, STAGES } from '../src/lib/partnerships.ts'
const opportunity = (patch={}) => ({id:'test',brandId:'test-brand',type:'ugc',stage:'Research',title:'',concept:'',fit:'',audienceWhy:'',formats:[],valueOffered:[],fee:'',nextAction:'Research brand',nextActionDate:localDate(),episodeIds:[],platforms:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),...patch})
test('new uncontacted brand without a concept starts with research and gets all pitch steps',()=>{ const plan=makeJourney(false,false); assert.equal(plan[0].stage,'Research'); assert.deepEqual(plan.slice(0,10).map(s=>s.label),['Research brand','Find product fit','Find contacts','Generate concepts','Choose concept','Create spec preview','Prepare pitch','Send email','Follow up by email','Track response']) })
test('contacted brand starts at response tracking without inventing completed steps',()=>{const plan=makeJourney(true,false);assert.equal(plan[0].stage,'Pitched');assert.ok(plan.every(s=>!s.completedAt))})
test('completion advances the journey and appends history, retaining prior logs',()=>{const o=opportunity({journey:makeJourney(false,false),activity:[{id:'old',text:'Earlier note',channel:'Notes',at:'2026-01-01'}]});const patch=completeAction(o);assert.equal(patch.nextAction,'Find product fit');assert.ok(patch.journey[0].completedAt);assert.equal(patch.activity.length,2);assert.equal(patch.nextActionDate,localDate(1));assert.equal(o.journey[0].completedAt,undefined)})
test('legacy record completion does not fabricate completed research',()=>{const p=completeAction(opportunity({stage:'Negotiating',nextAction:'Review usage rights'}));assert.equal(p.journey.filter(s=>s.completedAt).length,1);assert.ok(p.journey.every(s=>!['Research','Concept'].includes(s.stage)))})
test('manual stage change aligns upcoming work and preserves completed history',()=>{const o=opportunity({journey:[{id:'done',label:'Research brand',stage:'Research',completedAt:'2026-01-01'}]});const p=stageChange(o,'Agreed');assert.equal(p.stage,'Agreed');assert.equal(p.nextAction,'Confirm agreement');assert.equal(p.journey[0].id,'done');assert.ok(p.journey.slice(1).every(s=>STAGES.indexOf(s.stage)>=STAGES.indexOf('Agreed')))})
test('health distinguishes stale, due, scheduled and closed work',()=>{assert.equal(health(opportunity({nextActionDate:localDate(-8)})),'Stalled');assert.equal(health(opportunity()),'Needs attention');assert.equal(health(opportunity({nextActionDate:localDate(3)})),'Healthy');assert.equal(health(opportunity({stage:'Paid',nextActionDate:localDate(-10)})),'Healthy')})
test('each existing and new stage belongs to exactly one island region',()=>{const all=ISLAND_AREAS.flatMap(a=>a.stages);assert.deepEqual([...all].sort(),[...STAGES].sort());assert.equal(new Set(all).size,all.length)})
